export const AGORA_APP_ID = "79727223422d46f19514d0c5a40708ca"; // TODO: Replace with your actual Agora App ID
export const AGORA_TOKEN = null; // Token is null for test mode (if enabled in Agora Console) or needs to be generated by a token server
